import { UNMAPPED_SEGMENT } from "./entities";

/**
 * Static customer list in exact order as chuan.xlsx QEC review worksheet.
 */
export const STATIC_CUSTOMERS: string[] = [
  "Guardian",
  "Pharmadi (kho Sài Gòn 1)",
  "Phòng Khám Đa Khoa Quốc Tế CHAC",
  "Công ty Cổ phần Sóc Đỏ",
  "Waston",
  "Nhà thuốc An Khang (Kho AK Long Hậu)",
  "Nhà thuốc An Khang (Kho AK Trà Nóc)",
  "Công ty Dược phẩm Mạnh Tý",
  "Gourmet Shop Estella",
  "Duy Phương",
  "Shop Knguyen",
  "Nhà thuốc Đức Lan",
  "Nhà thuốc số 2",
  "OTC anh Đức",
  "Gourmet Shop Q2 Terrace",
  "Pharmadi (kho Hà Nội)",
  "Công ty CPTM và Phân Phối Hướng Dương",
  "Gourmet Shop Saigon Centre",
  "Chị Nhung (ĐTĐ)",
  "Medicare",
  "Bibomart",
  "Quầy thuốc Minh Phương",
  "Gourmet Shop An Phú",
  "Chị Nhung Yanhee",
  "An Bé Bé (Bình Lâm)",
  "Công ty TNHH Dược Phẩm Thành Sen",
  "Nhím Store",
  "Gourmet Shop Hà Nội",
  "Khách hàng (Cảnh)",
  "Vườn của bé",
  "Con Cưng Office",
  "Công ty TNHH Thực Phẩm - Mỹ Phẩm Nhật Việt",
  "Em Cảnh",
  "Bác sĩ Oanh",
  "Aeon Mall",
  "Khách lẻ trúng thưởng: Thanh Tuyền",
  "Khách lẻ trúng thưởng: Bùi Đan",
  "Khách lẻ trúng thưởng: Quốc Thy",
  "Khách lẻ trúng thưởng: Nguyễn Tường Vy",
  "Khách lẻ trúng thưởng: Mai An",
  "Khách lẻ trúng thưởng: Cao thị Bích Phượng",
  "Khách lẻ trúng thưởng: Nguyễn Khánh",
  "Khách lẻ trúng thưởng: Nguyễn Khánh (1)",
  "Khách lẻ trúng thưởng: Bạch Văn Luận",
  "Khách lẻ trúng thưởng: Phan Hà Trang",
  "Khách lẻ trúng thưởng: Nguyễn Thị Tường Vi",
  "Khách lẻ trúng thưởng: Nguyễn Huỳnh Minh Thư",
  "Nhà thuốc An Khang (Kho AK Bến Tre)",
  "Khách lẻ trúng thưởng: Thơm Giang",
  "Khách lẻ trúng thưởng: Phương",
  "Khách lẻ trúng thưởng: Cao Thị Mùi",
  "Khách lẻ trúng thưởng: Phùng Thanh Huyền",
  "Khách lẻ trúng thưởng: Nguyễn Thị Huyền",
  "Khách lẻ trúng thưởng: Chloe Nguyen",
  "Khách lẻ trúng thưởng: Cả ngỗ Vui Khỏe",
  "Khách lẻ trúng thưởng: Trần Thúy",
  "Khách lẻ trúng thưởng: Nguyễn Khánh Vy",
  "Khách lẻ trúng thưởng: Trần Minh Thu",
  "Khách lẻ trúng thưởng: Minh Thùy",
  "Khách lẻ trúng thưởng: Phạm Phương Anh",
  "Khách lẻ trúng thưởng: Trần Thư",
  "Khách lẻ trúng thưởng: Phương Trần",
  "Khách lẻ trúng thưởng: Đỗ Thị Diệu",
  "Khách lẻ trúng thưởng: Hoàng Thị Tâm",
  "Khách lẻ trúng thưởng: Thanh Thanh",
  "Khách lẻ trúng thưởng: An Nhiên",
  "Khách lẻ trúng thưởng: Na Na",
  "Khách lẻ trúng thưởng: Mai Lee",
  "Khách lẻ trúng thưởng: Thanh Hiền",
  "Khách lẻ trúng thưởng: Đào Thị Lan (3)",
  "Khách lẻ trúng thưởng: Linh Sunny",
  "Khách lẻ trúng thưởng: An An",
  "Khách lẻ trúng thưởng: Tú Uyên",
  "Khách lẻ trúng thưởng: Nguyễn Trần Thục Uyên",
  "Khách lẻ trúng thưởng: Nguyễn Đồng Đồng",
  "Khách lẻ trúng thưởng: Nguyễn Thị Kim",
  "Khách lẻ trúng thưởng: Đan Linh",
  "Khách lẻ trúng thưởng: Nguyễn Thanh Huyền",
  "Khách lẻ trúng thưởng: Đặng Hương",
  "Khách lẻ trúng thưởng: Hoàng Yến",
  "Khách lẻ trúng thưởng: Nguyễn Thị Minh Hằng",
  "Khách lẻ trúng thưởng: Nguyễn Trang",
  "Anh Tùng",
  "Quầy thuốc Kim Phương",
  "Công ty TNHH Thương mại dược phẩm Thanh Phương",
  "Em Mai (nhân viên)",
  "Khách lẻ trúng thưởng: Phương Linh",
  "Khách lẻ trúng thưởng: Nguyễn Thu Trang",
  "Khách lẻ trúng thưởng: Lan",
  "Khách lẻ trúng thưởng: Nguyễn Thu Trang (1)",
  "Khách lẻ trúng thưởng: Ngân Hoàng",
  "Khách lẻ trúng thưởng: Tuyên Be",
  "Khách lẻ trúng thưởng: Hà Huyền My",
  "Khách lẻ trúng thưởng: Nguyễn Hồng Thanh",
  "Khách lẻ trúng thưởng: Tùng",
  "Khách lẻ trúng thưởng: Thu Trang",
  "Khách lẻ trúng thưởng: Mai Anh",
  "Khách lẻ trúng thưởng: Hải Yến",
  "Khách lẻ trúng thưởng: Hải Đinh",
  "Khách lẻ trúng thưởng: Anna Trần",
  "Khách lẻ trúng thưởng: Quyen Do",
  "Khách lẻ trúng thưởng: Phùng Thư",
  "Khách lẻ trúng thưởng: Nguyễn Huyền",
  "Khách lẻ trúng thưởng: Pham Cừu Anh",
  "Khách lẻ trúng thưởng: Thùy Dương",
  "Khách lẻ trúng thưởng: Lê Ngân",
  "Khách lẻ trúng thưởng: Duyên",
  "Khách lẻ trúng thưởng: Mai Huyền",
  "Khách lẻ trúng thưởng: Trần Hoà",
  "Khách lẻ trúng thưởng: Thuỳ Dương (1)",
  "Khách lẻ trúng thưởng: Trần Tú Anh",
  "Khách lẻ trúng thưởng: Phạm Thanh Huyền",
  "Khách lẻ trúng thưởng: Nguyễn Thương",
  "Khách lẻ trúng thưởng: Vũ Thắm",
  "Khách lẻ trúng thưởng: Nguyễn Sương",
  "Công Ty TNHH TM Dược Phẩm Bảo Bình",
  "Nhà thuốc An Khang (Hub)",
  "Nhà Thuốc Trường Giang",
  "Ếch cốm (Tổng)",
  "Nhà thuốc Thắng Hương",
  "Nhà thuốc Đỗ Chí Thành",
  "Nhà thuốc Minh Anh IV",
  "Công ty TNHH Phát triển thương mại Trần Gia",
  "Công ty Cổ Phần Thế Giới Di Động (Ava_HCM - Kho Ava World Tân Bình)",
  "Nhà thuốc GPP Minh Châu",
  "Nhà thuốc Nhị Trưng",
  "Nhà Thuốc Mỹ Duyên",
  "Kim Hiền Baby",
  "Thuế",
  "Tạ Chiêu An (nhân viên)",
  "Nhà phân phối Thành Văn",
  "Careace",
  "Nhà thuốc An Khang - Phú Quốc",
  "Khách lẻ trúng thưởng: Lê Thị Mỹ Dung",
  "Khách lẻ trúng thưởng: Nguyễn Tuyết Nhi",
  "Khách lẻ trúng thưởng: Trần Thị Thu Trang",
  "Khách lẻ trúng thưởng: Nguyễn  Thanh Vỹ",
  "Uyên (nhân viên)",
  "Kỳ Duyên Beauty Store",
  "Shop Khang Baby",
  "Nhà thuốc Quỳnh Thi",
  "anh Minh (MKT)",
  "Nhà thuốc Phước Thiện",
  "Phòng khám nội tiêu hóa gan mật Bác sĩ Thuận",
  "Phòng mạch Bác sĩ Anh Thư",
  "Bun Bếp Quán",
  "Em Liên (nhân viên công ty)",
  "Top Milk",
  "Khách lẻ: Nhung Nguyễn",
  "Khách lẻ: Thùy Dung",
  "Nhà phân phối Hoàng Hải - Vĩnh Phúc",
  "Tin’s House Phú Quốc",
  "Nhà Thuốc Kim Anh 2",
  "Khách lẻ: Như Quỳnh",
  "Khách lẻ trúng thưởng: Linh Khánh",
  "Khách lẻ trúng thưởng: Đào Thị Lan (1)",
  "Khách lẻ trúng thưởng: Sang Thúy My",
  "Khách lẻ trúng thưởng: Bống Bi",
  "Shop Knguyen (Đan Phượng)",
  "Guardian (PO)",
  "Hộ kinh doanh Vũ Thị Hòa (WS Ngọc Trâm)",
  "Triết Minh (nhân viên)",
  "Annam Gourmet Hai Bà Trưng",
  "Alibaby",
  "Nhà thuốc An Khang (Kho AK Đà Nẵng)",
  "Khách lẻ: Đào Châm (VNSHOP)",
  "Quầy Thuốc Sức Khỏe",
  "Quân (nhân viên)",
  "Dola' House (Baby's Corner)",
  "Shop sữa Phương Anh",
  "Nhà thuốc Phương Linh",
  "Nhà phân phối Nghệ An",
  "Khách lẻ: Tu Nguyen Khanh Trang (VNSHOP)",
  "Khách lẻ: Duy Tân (VNSHOP)",
  "Min (nhân viên)",
  "Mai Ly",
  "Khách lẻ: Nguyễn Văn Thành (VNSHOP)",
  "CTCT Thế Giới Di Động - Tòa nhà MWG",
  "WS Như Trần Ngọc (cô Xuyến)",
  "Betty Baby",
  "Khách lẻ trúng thưởng: Song Ngọc Phương Trâm",
  "Khách lẻ trúng thưởng: Hà Vy",
  "Khách lẻ trúng thưởng: Hương Đình",
  "Nhà thuốc Bạch Yến",
  "Shop Babysun",
  "Khách lẻ: chị Hiền",
  "Khách lẻ: Vo Van Tinh (VNSHOP)",
  "Khách lẻ: Ohsaki (VNSHOP)",
  "Khách lẻ: Tân Trần (VNSHOP)",
  "Gourmet Shop Landmark 81",
  "Khách lẻ: Lê Tấn Phát (VNSHOP)",
  "Khách lẻ trúng thưởng: Nguyễn Chúc",
  "Khách lẻ trúng thưởng: Nguyễn Phi Phục",
  "Khách lẻ trúng thưởng: Shop Knguyen",
  "Khách lẻ: Nguyễn Nhung (VNSHOP)",
  "Nhà thuốc Vinpharmacy",
  "Gourmet Shop Vincom Plaza Long Bien HN",
  "Tuấn Bùi",
  "Công ty Kim Sa Group",
  "Nhà thuốc Thái Ngọc",
  "Shop Thảo Nguyên",
  "Khách lẻ: Nguyễn Thị Hường (VNSHOP)",
  "Gourmet Shop Ascentia",
  "Gourmet Shop Phú Mỹ Hưng",
  "Gourmet Shop Feliz Vista",
  "Khách lẻ trúng thưởng: Dung Bubi",
  "Khách lẻ trúng thưởng: Sunshine",
  "Khách lẻ trúng thưởng: Vũ Thu Hường",
  "Khách lẻ trúng thưởng: Đào Thị Lan",
  "Khách lẻ trúng thưởng: Bảo An",
  "Khách lẻ trúng thưởng: Yến Yến",
  "Cộng tác viên: Trà Thanh Vân",
  "Med 247",
  "Phòng khám Kokasi",
  "Baby Mark - Trạm Thực Nghiệm",
  "OTC Hiển Vinh - Vũng Tàu.",
  "Cửa hàng Baby Thu Cầm",
  "Shop Hato Baby",
  "OTC Trọng Nghĩa",
  "Hàng PG",
  "Ếch Cốm 1 - Tân Mai - Hoàng Mai",
  "Nhà thuốc Hồng Việt",
  "Subibin",
  "Công ty CP Lebebee",
  "Võ Thị Hoài Thương",
  "Khách lẻ: Nguyễn Thị Giang Tâm (VNSHOP)",
  "Khách lẻ: Nguyễn Thiên Hương (VNSHOP)",
  "Khách lẻ: Vũ Hồng Loan (VNSHOP)",
  "Quầy thuốc 102",
  "chị Hà (nhân viên)",
  "Ngô Sỹ Hiệp",
  "Đỗ Văn Chính",
  "Suri",
  "Khách lẻ: Cao Thị Chính (Vnshop)",
  "Nhà phân phối Quảng Ninh",
  "Thiên Hương Group",
  "Công ty Cổ Phần Omicare",
  "Anh Khải (Nhân viên công ty)",
  "Khách lẻ: Nguyễn Thùy Minh (Vnshop)",
  "Trung Sơn",
  "Hải Yến",
  "Chuỗi Mẹ và bé Mỹ Linh An Giang",
  "Anh Tuấn (hàng Mẹ & Bé)",
  "Cô Xuyến",
  "Nhà phân phối Nguyệt Hải",
  "Nhà thuốc Tiến Trang",
  "Mr Phúc",
  "Chuỗi Mint Cosmetic",
  "Nguyễn Anh Tuấn",
  "Dr. Rossie - Thực dưỡng khoẻ đẹp",
  "Bệnh viện Vinmec",
  "Công Ty TNHH Bảo Hưng Fruits",
  "Thành Văn",
  "Siêu thị Hùng Vương",
  "Công ty TNHH & PP Mạch Huy",
  "Hộ kinh doanh Vũ Thị Hòa",
  "Phòng mạch Bác sĩ Thu Hậu",
  "Chị My (nhóm Zalo)",
  "Khách lẻ: Lệ (VN Shop)",
  "Gourmet Shop Saigon Pearl",
  "Con Cưng",
  "Trần Gia",
  "Khách hàng lẻ: Đỗ Thị Cúc",
  "Nhà thuốc Phương Thảo",
  "Kids Plaza",
  "Bibonmart",
  "An Nam Bỉm Sữa (Nguyễn Văn Tiến)",
  "Khách lẻ: Chị Loan (Hải)",
  "Nhà thuốc Hoàng Lê",
  "Nhà thuốc Minh Chính",
  "Pharmadi",
  "Nhà thuốc Thiên Đức",
  "Nhà thuốc Mỹ Dung",
  "Bệnh viện Hùng Vương",
  "An Khang",
  "Quầy thuốc Thành Chi",
  "Chưa có tên",
  "Hebela",
  "Công ty Đồng Bằng",
  "Nhà thuốc Nhân Tâm",
  "Công ty TNHH Thương Mại Dịch Vụ Tổng Hợp Y Tế Tiến Thanh",
  "Đoàn Trung Phú, Công Ty Cổ Phần Thế Giới Di Động",
  "Nhà thuốc Vân Chi",
  "Công ty TNHH Lê Lâm Ngọc",
  "Phòng khám Đa Khoa Thuận Kiều",
  "Nhà thuốc Khánh Vân",
  "Công ty TNHH Dược phẩm Propharma",
  "Bác sĩ Vinh Hoàng",
  "Khách lẻ Nguyễn Quyết Chiến",
  "Khách lẻ Lê Thị Thanh Triều (VNSHOP)",
  "Nhà thuốc Ngọc Tuyết",
  "Khách lẻ (Cảnh)",
  "Quầy thuốc Hoài Tính",
  "Chị Châu",
  "Bác sĩ Nguyễn Văn Hậu",
];

/**
 * Static customer → segment mapping extracted from chuan.xlsx QEC review (row 29+).
 * 296 unique customers mapped to their business segment.
 */
const CUSTOMER_SEGMENT_MAP = new Map<string, string>([
  ["Guardian", "MT"],
  ["Pharmadi (kho Sài Gòn 1)", "WS"],
  ["Phòng Khám Đa Khoa Quốc Tế CHAC", "ETC"],
  ["Công ty Cổ phần Sóc Đỏ", "Ecom"],
  ["Waston", "MT"],
  ["Nhà thuốc An Khang (Kho AK Long Hậu)", "AK"],
  ["Nhà thuốc An Khang (Kho AK Trà Nóc)", "AK"],
  ["Công ty Dược phẩm Mạnh Tý", "OTC"],
  ["Gourmet Shop Estella", "MT"],
  ["Duy Phương", "IDP"],
  ["Shop Knguyen", "B&M"],
  ["Nhà thuốc Đức Lan", "OTC"],
  ["Nhà thuốc số 2", "OTC"],
  ["OTC anh Đức", "WS"],
  ["Gourmet Shop Q2 Terrace", "MT"],
  ["Pharmadi (kho Hà Nội)", "WS"],
  ["Công ty CPTM và Phân Phối Hướng Dương", "WS"],
  ["Gourmet Shop Saigon Centre", "MT"],
  ["Chị Nhung (ĐTĐ)", "IDP"],
  ["Medicare", "MT"],
  ["Bibomart", "MT"],
  ["Quầy thuốc Minh Phương", "OTC"],
  ["Gourmet Shop An Phú", "MT"],
  ["Chị Nhung Yanhee", "IDP"],
  ["An Bé Bé (Bình Lâm)", "IDP"],
  ["Công ty TNHH Dược Phẩm Thành Sen", "OTC"],
  ["Nhím Store", "B&M"],
  ["Gourmet Shop Hà Nội", "MT"],
  ["Khách hàng (Cảnh)", "IDP"],
  ["Vườn của bé", "B&M"],
  ["Con Cưng Office", "B&M"],
  ["Công ty TNHH Thực Phẩm - Mỹ Phẩm Nhật Việt", "Ecom"],
  ["Em Cảnh", "IDP"],
  ["Bác sĩ Oanh", "IDP"],
  ["Aeon Mall", "MT"],
  ["Khách lẻ trúng thưởng: Thanh Tuyền", "IDP"],
  ["Khách lẻ trúng thưởng: Bùi Đan", "IDP"],
  ["Khách lẻ trúng thưởng: Quốc Thy", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Tường Vy", "IDP"],
  ["Khách lẻ trúng thưởng: Mai An", "IDP"],
  ["Khách lẻ trúng thưởng: Cao thị Bích Phượng", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Khánh", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Khánh (1)", "IDP"],
  ["Khách lẻ trúng thưởng: Bạch Văn Luận", "IDP"],
  ["Khách lẻ trúng thưởng: Phan Hà Trang", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thị Tường Vi", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Huỳnh Minh Thư", "IDP"],
  ["Nhà thuốc An Khang (Kho AK Bến Tre)", "AK"],
  ["Khách lẻ trúng thưởng: Thơm Giang", "IDP"],
  ["Khách lẻ trúng thưởng: Phương", "IDP"],
  ["Khách lẻ trúng thưởng: Cao Thị Mùi", "IDP"],
  ["Khách lẻ trúng thưởng: Phùng Thanh Huyền", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thị Huyền", "IDP"],
  ["Khách lẻ trúng thưởng: Chloe Nguyen", "IDP"],
  ["Khách lẻ trúng thưởng: Cả ngỗ Vui Khỏe", "IDP"],
  ["Khách lẻ trúng thưởng: Trần Thúy", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Khánh Vy", "IDP"],
  ["Khách lẻ trúng thưởng: Trần Minh Thu", "IDP"],
  ["Khách lẻ trúng thưởng: Minh Thùy", "IDP"],
  ["Khách lẻ trúng thưởng: Phạm Phương Anh", "IDP"],
  ["Khách lẻ trúng thưởng: Trần Thư", "IDP"],
  ["Khách lẻ trúng thưởng: Phương Trần", "IDP"],
  ["Khách lẻ trúng thưởng: Đỗ Thị Diệu", "IDP"],
  ["Khách lẻ trúng thưởng: Hoàng Thị Tâm", "IDP"],
  ["Khách lẻ trúng thưởng: Thanh Thanh", "IDP"],
  ["Khách lẻ trúng thưởng: An Nhiên", "IDP"],
  ["Khách lẻ trúng thưởng: Na Na", "IDP"],
  ["Khách lẻ trúng thưởng: Mai Lee", "IDP"],
  ["Khách lẻ trúng thưởng: Thanh Hiền", "IDP"],
  ["Khách lẻ trúng thưởng: Đào Thị Lan (3)", "IDP"],
  ["Khách lẻ trúng thưởng: Linh Sunny", "IDP"],
  ["Khách lẻ trúng thưởng: An An", "IDP"],
  ["Khách lẻ trúng thưởng: Tú Uyên", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Trần Thục Uyên", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Đồng Đồng", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thị Kim", "IDP"],
  ["Khách lẻ trúng thưởng: Đan Linh", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thanh Huyền", "IDP"],
  ["Khách lẻ trúng thưởng: Đặng Hương", "IDP"],
  ["Khách lẻ trúng thưởng: Hoàng Yến", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thị Minh Hằng", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Trang", "IDP"],
  ["Anh Tùng", "IDP"],
  ["Quầy thuốc Kim Phương", "OTC"],
  ["Công ty TNHH Thương mại dược phẩm Thanh Phương", "OTC"],
  ["Em Mai (nhân viên)", "IDP"],
  ["Khách lẻ trúng thưởng: Phương Linh", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thu Trang", "IDP"],
  ["Khách lẻ trúng thưởng: Lan", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thu Trang (1)", "IDP"],
  ["Khách lẻ trúng thưởng: Ngân Hoàng", "IDP"],
  ["Khách lẻ trúng thưởng: Tuyên Be", "IDP"],
  ["Khách lẻ trúng thưởng: Hà Huyền My", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Hồng Thanh", "IDP"],
  ["Khách lẻ trúng thưởng: Tùng", "IDP"],
  ["Khách lẻ trúng thưởng: Thu Trang", "IDP"],
  ["Khách lẻ trúng thưởng: Mai Anh", "IDP"],
  ["Khách lẻ trúng thưởng: Hải Yến", "IDP"],
  ["Khách lẻ trúng thưởng: Hải Đinh", "IDP"],
  ["Khách lẻ trúng thưởng: Anna Trần", "IDP"],
  ["Khách lẻ trúng thưởng: Quyen Do", "IDP"],
  ["Khách lẻ trúng thưởng: Phùng Thư", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Huyền", "IDP"],
  ["Khách lẻ trúng thưởng: Pham Cừu Anh", "IDP"],
  ["Khách lẻ trúng thưởng: Thùy Dương", "IDP"],
  ["Khách lẻ trúng thưởng: Lê Ngân", "IDP"],
  ["Khách lẻ trúng thưởng: Duyên", "IDP"],
  ["Khách lẻ trúng thưởng: Mai Huyền", "IDP"],
  ["Khách lẻ trúng thưởng: Trần Hoà", "IDP"],
  ["Khách lẻ trúng thưởng: Thuỳ Dương (1)", "IDP"],
  ["Khách lẻ trúng thưởng: Trần Tú Anh", "IDP"],
  ["Khách lẻ trúng thưởng: Phạm Thanh Huyền", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Thương", "IDP"],
  ["Khách lẻ trúng thưởng: Vũ Thắm", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Sương", "IDP"],
  ["Công Ty TNHH TM Dược Phẩm Bảo Bình", "OTC"],
  ["Nhà thuốc An Khang (Hub)", "AK"],
  ["Nhà Thuốc Trường Giang", "OTC"],
  ["Ếch cốm (Tổng)", "IDP"],
  ["Nhà thuốc Thắng Hương", "IDP"],
  ["Nhà thuốc Đỗ Chí Thành", "IDP"],
  ["Nhà thuốc Minh Anh IV", "OTC"],
  ["Công ty TNHH Phát triển thương mại Trần Gia", "Ecom"],
  ["Công ty Cổ Phần Thế Giới Di Động (Ava_HCM - Kho Ava World Tân Bình)", "B&M"],
  ["Nhà thuốc GPP Minh Châu", "OTC"],
  ["Nhà thuốc Nhị Trưng", "OTC"],
  ["Nhà Thuốc Mỹ Duyên", "OTC"],
  ["Kim Hiền Baby", "B&M"],
  ["Thuế", "IDP"],
  ["Tạ Chiêu An (nhân viên)", "IDP"],
  ["Nhà phân phối Thành Văn", "WS"],
  ["Careace", "OTC"],
  ["Nhà thuốc An Khang - Phú Quốc", "OTC"],
  ["Khách lẻ trúng thưởng: Lê Thị Mỹ Dung", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Tuyết Nhi", "IDP"],
  ["Khách lẻ trúng thưởng: Trần Thị Thu Trang", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn  Thanh Vỹ", "IDP"],
  ["Uyên (nhân viên)", "IDP"],
  ["Kỳ Duyên Beauty Store", "KEY"],
  ["Shop Khang Baby", "B&M"],
  ["Nhà thuốc Quỳnh Thi", "OTC"],
  ["anh Minh (MKT)", "IDP"],
  ["Nhà thuốc Phước Thiện", "OTC"],
  ["Phòng khám nội tiêu hóa gan mật Bác sĩ Thuận", "ETC"],
  ["Phòng mạch Bác sĩ Anh Thư", "IDP"],
  ["Bun Bếp Quán", "IDP"],
  ["Em Liên (nhân viên công ty)", "IDP"],
  ["Top Milk", "B&M"],
  ["Khách lẻ: Nhung Nguyễn", "IDP"],
  ["Khách lẻ: Thùy Dung", "IDP"],
  ["Nhà phân phối Hoàng Hải - Vĩnh Phúc", "WS"],
  ["Tin’s House Phú Quốc", "B&M"],
  ["Nhà Thuốc Kim Anh 2", "OTC"],
  ["Khách lẻ: Như Quỳnh", "IDP"],
  ["Khách lẻ trúng thưởng: Linh Khánh", "IDP"],
  ["Khách lẻ trúng thưởng: Đào Thị Lan (1)", "IDP"],
  ["Khách lẻ trúng thưởng: Sang Thúy My", "IDP"],
  ["Khách lẻ trúng thưởng: Bống Bi", "IDP"],
  ["Shop Knguyen (Đan Phượng)", "IDP"],
  ["Guardian (PO)", "MT"],
  ["Hộ kinh doanh Vũ Thị Hòa (WS Ngọc Trâm)", "WS"],
  ["Triết Minh (nhân viên)", "IDP"],
  ["Annam Gourmet Hai Bà Trưng", "MT"],
  ["Alibaby", "B&M"],
  ["Nhà thuốc An Khang (Kho AK Đà Nẵng)", "AK"],
  ["Khách lẻ: Đào Châm (VNSHOP)", "IDP"],
  ["Quầy Thuốc Sức Khỏe", "OTC"],
  ["Quân (nhân viên)", "IDP"],
  ["Dola' House (Baby's Corner)", "B&M"],
  ["Shop sữa Phương Anh", "B&M"],
  ["Nhà thuốc Phương Linh", "OTC"],
  ["Nhà phân phối Nghệ An", "IDP"],
  ["Khách lẻ: Tu Nguyen Khanh Trang (VNSHOP)", "IDP"],
  ["Khách lẻ: Duy Tân (VNSHOP)", "IDP"],
  ["Min (nhân viên)", "IDP"],
  ["Mai Ly", "Ecom"],
  ["Khách lẻ: Nguyễn Văn Thành (VNSHOP)", "IDP"],
  ["CTCT Thế Giới Di Động - Tòa nhà MWG", "B&M"],
  ["WS Như Trần Ngọc (cô Xuyến)", "B&M"],
  ["Betty Baby", "B&M"],
  ["Khách lẻ trúng thưởng: Song Ngọc Phương Trâm", "IDP"],
  ["Khách lẻ trúng thưởng: Hà Vy", "IDP"],
  ["Khách lẻ trúng thưởng: Hương Đình", "IDP"],
  ["Nhà thuốc Bạch Yến", "OTC"],
  ["Shop Babysun", "B&M"],
  ["Khách lẻ: chị Hiền", "IDP"],
  ["Khách lẻ: Vo Van Tinh (VNSHOP)", "IDP"],
  ["Khách lẻ: Ohsaki (VNSHOP)", "IDP"],
  ["Khách lẻ: Tân Trần (VNSHOP)", "IDP"],
  ["Gourmet Shop Landmark 81", "MT"],
  ["Khách lẻ: Lê Tấn Phát (VNSHOP)", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Chúc", "IDP"],
  ["Khách lẻ trúng thưởng: Nguyễn Phi Phục", "IDP"],
  ["Khách lẻ trúng thưởng: Shop Knguyen", "IDP"],
  ["Khách lẻ: Nguyễn Nhung (VNSHOP)", "IDP"],
  ["Nhà thuốc Vinpharmacy", "OTC"],
  ["Gourmet Shop Vincom Plaza Long Bien HN", "MT"],
  ["Tuấn Bùi", "Ecom"],
  ["Công ty Kim Sa Group", "Ecom"],
  ["Nhà thuốc Thái Ngọc", "OTC"],
  ["Shop Thảo Nguyên", "B&M"],
  ["Khách lẻ: Nguyễn Thị Hường (VNSHOP)", "IDP"],
  ["Gourmet Shop Ascentia", "MT"],
  ["Gourmet Shop Phú Mỹ Hưng", "MT"],
  ["Gourmet Shop Feliz Vista", "MT"],
  ["Khách lẻ trúng thưởng: Dung Bubi", "IDP"],
  ["Khách lẻ trúng thưởng: Sunshine", "IDP"],
  ["Khách lẻ trúng thưởng: Vũ Thu Hường", "IDP"],
  ["Khách lẻ trúng thưởng: Đào Thị Lan", "IDP"],
  ["Khách lẻ trúng thưởng: Bảo An", "IDP"],
  ["Khách lẻ trúng thưởng: Yến Yến", "B&M"],
  ["Cộng tác viên: Trà Thanh Vân", "IDP"],
  ["Med 247", "ETC"],
  ["Phòng khám Kokasi", "ETC"],
  ["Baby Mark - Trạm Thực Nghiệm", "B&M"],
  ["OTC Hiển Vinh - Vũng Tàu.", "OTC"],
  ["Cửa hàng Baby Thu Cầm", "B&M"],
  ["Shop Hato Baby", "B&M"],
  ["OTC Trọng Nghĩa", "OTC"],
  ["Hàng PG", "IDP"],
  ["Ếch Cốm 1 - Tân Mai - Hoàng Mai", "B&M"],
  ["Nhà thuốc Hồng Việt", "OTC"],
  ["Subibin", "WS"],
  ["Công ty CP Lebebee", "B&M"],
  ["Võ Thị Hoài Thương", "IDP"],
  ["Khách lẻ: Nguyễn Thị Giang Tâm (VNSHOP)", "IDP"],
  ["Khách lẻ: Nguyễn Thiên Hương (VNSHOP)", "B&M"],
  ["Khách lẻ: Vũ Hồng Loan (VNSHOP)", "IDP"],
  ["Quầy thuốc 102", "OTC"],
  ["chị Hà (nhân viên)", "IDP"],
  ["Ngô Sỹ Hiệp", "IDP"],
  ["Đỗ Văn Chính", "IDP"],
  ["Suri", "B&M"],
  ["Khách lẻ: Cao Thị Chính (Vnshop)", "IDP"],
  ["Nhà phân phối Quảng Ninh", "WS"],
  ["Thiên Hương Group", "Ecom"],
  ["Công ty Cổ Phần Omicare", "OTC"],
  ["Anh Khải (Nhân viên công ty)", "IDP"],
  ["Khách lẻ: Nguyễn Thùy Minh (Vnshop)", "IDP"],
  ["Trung Sơn", "MT"],
  ["Hải Yến", "IDP"],
  ["Chuỗi Mẹ và bé Mỹ Linh An Giang", "B&M"],
  ["Anh Tuấn (hàng Mẹ & Bé)", "Ecom"],
  ["Cô Xuyến", "B&M"],
  ["Nhà phân phối Nguyệt Hải", "WS"],
  ["Nhà thuốc Tiến Trang", "OTC"],
  ["Mr Phúc", "IDP"],
  ["Chuỗi Mint Cosmetic", "H&B"],
  ["Nguyễn Anh Tuấn", "IDP"],
  ["Dr. Rossie - Thực dưỡng khoẻ đẹp", "OTC"],
  ["Bệnh viện Vinmec", "ETC"],
  ["Công Ty TNHH Bảo Hưng Fruits", "WS"],
  ["Thành Văn", "WS"],
  ["Siêu thị Hùng Vương", "ETC"],
  ["Công ty TNHH & PP Mạch Huy", "WS"],
  ["Hộ kinh doanh Vũ Thị Hòa", "WS"],
  ["Phòng mạch Bác sĩ Thu Hậu", "ETC"],
  ["Chị My (nhóm Zalo)", "IDP"],
  ["Khách lẻ: Lệ (VN Shop)", "IDP"],
  ["Gourmet Shop Saigon Pearl", "MT"],
  ["Con Cưng", "MT"],
  ["Trần Gia", "KEY"],
  ["Khách hàng lẻ: Đỗ Thị Cúc", "IDP"],
  ["Nhà thuốc Phương Thảo", "OTC"],
  ["Kids Plaza", "B&M"],
  ["Bibonmart", "B&M"],
  ["An Nam Bỉm Sữa (Nguyễn Văn Tiến)", "B&M"],
  ["Khách lẻ: Chị Loan (Hải)", "IDP"],
  ["Nhà thuốc Hoàng Lê", "OTC"],
  ["Nhà thuốc Minh Chính", "OTC"],
  ["Pharmadi", "WS"],
  ["Nhà thuốc Thiên Đức", "OTC"],
  ["Nhà thuốc Mỹ Dung", "OTC"],
  ["Bệnh viện Hùng Vương", "ETC"],
  ["An Khang", "MT"],
  ["Quầy thuốc Thành Chi", "OTC"],
  ["Chưa có tên", "IDP"],
  ["Hebela", "Ecom"],
  ["Công ty Đồng Bằng", "OTC"],
  ["Nhà thuốc Nhân Tâm", "OTC"],
  ["Công ty TNHH Thương Mại Dịch Vụ Tổng Hợp Y Tế Tiến Thanh", "ETC"],
  ["Đoàn Trung Phú, Công Ty Cổ Phần Thế Giới Di Động", "B&M"],
  ["Nhà thuốc Vân Chi", "OTC"],
  ["Công ty TNHH Lê Lâm Ngọc", "IDP"],
  ["Phòng khám Đa Khoa Thuận Kiều", "ETC"],
  ["Nhà thuốc Khánh Vân", "OTC"],
  ["Công ty TNHH Dược phẩm Propharma", "OTC"],
  ["Bác sĩ Vinh Hoàng", "ETC"],
  ["Khách lẻ Nguyễn Quyết Chiến", "IDP"],
  ["Khách lẻ Lê Thị Thanh Triều (VNSHOP)", "Ecom"],
  ["Nhà thuốc Ngọc Tuyết", "OTC"],
  ["Khách lẻ (Cảnh)", "IDP"],
  ["Quầy thuốc Hoài Tính", "OTC"],
  ["Chị Châu", "IDP"],
  ["Bác sĩ Nguyễn Văn Hậu", "ETC"],
]);

/**
 * Customer name corrections: raw Data nguồn names that differ from QEC review mapping.
 */
const NAME_CORRECTIONS = new Map<string, string>([
  ["Hộ kinh doanh Vũ Thị Hòa (NPP Ngọc Trâm)", "Hộ kinh doanh Vũ Thị Hòa (WS Ngọc Trâm)"],
  ["NPP Như Trần Ngọc (cô Xuyến)", "WS Như Trần Ngọc (cô Xuyến)"],
]);

/**
 * Normalize customer name by applying known corrections.
 */
export function normalizeCustomerName(name: string): string {
  return NAME_CORRECTIONS.get(name) ?? name;
}

/**
 * Look up segment for a customer. Returns UNMAPPED_SEGMENT if not found.
 */
export function lookupSegment(customerName: string): string {
  return CUSTOMER_SEGMENT_MAP.get(customerName) ?? UNMAPPED_SEGMENT;
}

/**
 * Map raw DSR name ("Người thực hiện") to standardized DSR group.
 */
const DSR_MAP = new Map<string, string>([
  ["Trương Minh Cảnh", "TRUONG MINH CANH"],
  ["Nguyễn Tùng", "TRUONG MINH CANH"],
  ["Kha Văn Long", "TRUONG MINH CANH"],
  ["Nguyễn Văn Khải", "TRUONG MINH CANH"],
  ["Đỗ Văn Chính", "TRUONG MINH CANH"],
  ["Ngô Sỹ Hiệp", "TRUONG MINH CANH"],
  ["Lê Quang Quân", "TRUONG MINH CANH"],
  ["Tôn Long Gia Bảo", "TRUONG MINH CANH"],
  ["Nguyễn Đăng Đạt", "TRUONG MINH CANH"],
  ["Đỗ Quang Long", "TRUONG MINH CANH"],
  ["Nguyễn Thị Triết Minh", "TRUONG MINH CANH"],
  ["Lê Quang Chơn", "TRUONG MINH CANH"],
  ["Trịnh Ngọc Hà", "TRINH NGOC HA"],
  ["chị Trinh", "TRINH NGOC HA"],
  ["Chị Trinh", "TRINH NGOC HA"],
  ["Tạ Chiêu An", "CHIEU AN"],
]);

export const DSR_ORDER = ["TRUONG MINH CANH", "TRINH NGOC HA", "CHIEU AN"];

export function lookupDsr(rawDsr: string): string {
  const trimmed = rawDsr.trim();
  return DSR_MAP.get(trimmed) ?? "TRUONG MINH CANH";
}

